### ISSUE TITLE
Java exception occurred

### ISSUE THREAD

**Issue by ericjohnson97** [tpfau/xlread#1]
I got the following error on my matlab 2018b setup

```
Java exception occurred:
java.lang.IllegalArgumentException: Your InputStream
was neither an OLE2 stream, nor an OOXML stream

	at
    org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:75)

```
I have xlread on my matlab path and the following on the java path 
```
javaaddpath('poi_library/dom4j-1.6.1.jar')
javaaddpath('poi_library/poi-ooxml-3.8-20120326.jar')
javaaddpath('poi_library/xmlbeans-2.3.0.jar')
javaaddpath('poi_library/poi-ooxml-schemas-3.8-20120326.jar')
javaaddpath('poi_library/poi-3.8-20120326.jar')
javaaddpath('poi_library/stax-api-1.0.1.jar')
```

let me know if I am missing a setup step, or some other configuration issue.

Thank in advance!

**Comment by tpfau** [comment]
Hmm..
Do you have the text analytics toolbox installed?
If so, please uninstall it, as it ships with a broken POI library.
Other than that I would need the input data you use to get this error, as I currently don't have an idea, what might be causing it.

**Comment by tpfau** [comment]
Closing assuming it was a text analytics toolbox issue
